# Generated by Django 4.2.2 on 2023-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret_key',
        ),
        migrations.AddField(
            model_name='clients',
            name='account_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
