# Generated by Django 4.2.2 on 2023-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
