# Generated by Django 4.2.2 on 2023-09-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_otp_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
