# Generated by Django 4.2.2 on 2023-07-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clients_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='username',
            new_name='client',
        ),
    ]
