# Generated by Django 4.2.2 on 2023-07-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_clients_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client',
            new_name='username',
        ),
    ]
