# Generated by Django 4.2.2 on 2023-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enquiry_name_enquiry_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='upi_num_or_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
