# Generated by Django 4.2.2 on 2023-08-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clients'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='payments',
        ),
    ]
