# Generated by Django 4.2.2 on 2023-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_clients_is_blocked'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
