# Generated by Django 4.2.2 on 2023-08-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bookings_client_bookings_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='client',
        ),
        migrations.AddField(
            model_name='bookings',
            name='turf_added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
