# Generated by Django 4.2.2 on 2023-08-16 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='timestamp_enquiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
