# Generated by Django 4.2.2 on 2023-07-30 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_is_blocked_alter_customers_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='customers',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
