# Generated by Django 4.2.2 on 2023-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='booked_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
