# Generated by Django 4.2.2 on 2023-08-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_reservation_date_reservation_booked_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='booked_date',
            new_name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_date',
        ),
    ]
