# Generated by Django 4.2.2 on 2023-08-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation_id',
            field=models.IntegerField(default=''),
        ),
    ]
