# Generated by Django 4.2.2 on 2023-08-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_payment_reservation_payment_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
