# Generated by Django 4.2.2 on 2023-08-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_payment_reservation'),
        ('accounts', '0015_remove_payment_reservation_id_payment_reservation_and_more'),
    ]

    operations = [
    ]
